import { AiContextGenerator } from '../src/services/ai-context-generator.js';
import fs from 'fs';
import path from 'path';
import os from 'os';
import { fileURLToPath } from 'url';
import { execFileSync } from 'child_process';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

describe('AiContextGenerator', () => {
    let tempDir: string;
    let generator: AiContextGenerator;

    beforeEach(() => {
        tempDir = fs.mkdtempSync(path.join(os.tmpdir(), 'n8n-ai-test-'));
        generator = new AiContextGenerator();
    });

    afterEach(() => {
        fs.rmSync(tempDir, { recursive: true, force: true });
    });

    describe('Context root bootstrap', () => {
        test('creates lightweight AGENTS.md, VS Code agents, and local skills on fresh install', async () => {
            const version = '1.0.0';
            await generator.generate(tempDir, version);

            const agentsPath = path.join(tempDir, 'AGENTS.md');
            const architectAgentPath = path.join(tempDir, '.github/agents/n8n-architect.agent.md');
            const architectSkillPath = path.join(tempDir, '.agents/skills/n8n-architect/SKILL.md');

            expect(fs.existsSync(agentsPath)).toBe(true);
            expect(fs.existsSync(architectAgentPath)).toBe(true);
            expect(fs.existsSync(architectSkillPath)).toBe(true);

            const agentsContent = fs.readFileSync(agentsPath, 'utf-8');
            expect(agentsContent).toContain('<!-- n8n-as-code-start -->');
            expect(agentsContent).toContain(`- n8n version at generation time: ${version}`);
            expect(agentsContent).toContain('This file is generated by');
            expect(agentsContent).toContain('.github/agents/n8n-architect.agent.md');
            expect(agentsContent).toContain('.agents/skills/n8n-architect/SKILL.md');
            expect(agentsContent).toContain('n8nac backend resolution remains the only source');
            expect(agentsContent).toContain('env status --json');
            expect(agentsContent).not.toContain('workspace migrate --json');
            expect(agentsContent).not.toContain('workspace status --json');
            expect(agentsContent).toContain('npx --yes @n8n-as-code/n8n-manager');
            expect(agentsContent).toContain('Use the returned `workflowsPath` exactly as provided.');
            expect(agentsContent).toContain('Do not reconstruct `workflowsPath`');
            expect(agentsContent).toContain('legacy sync fields');
            expect(architectSkillPath && fs.readFileSync(architectSkillPath, 'utf-8')).toContain('--workflows-path workflows/<name>');
            expect(architectSkillPath && fs.readFileSync(architectSkillPath, 'utf-8')).not.toContain('--sync-folder workflows/<name>');
            expect(agentsContent).toContain('<!-- n8n-as-code-end -->');
        });

        test('uses matching published dist tags for portable n8nac and n8n-manager commands', async () => {
            await generator.generate(tempDir, '1.0.0', 'next');

            const agentsContent = fs.readFileSync(path.join(tempDir, 'AGENTS.md'), 'utf-8');
            const architectAgent = fs.readFileSync(path.join(tempDir, '.github/agents/n8n-architect.agent.md'), 'utf-8');
            const architectSkill = fs.readFileSync(path.join(tempDir, '.agents/skills/n8n-architect/SKILL.md'), 'utf-8');

            expect(agentsContent).toContain('npx --yes n8nac@next env status --json');
            expect(agentsContent).not.toContain('npx --yes n8nac@next workspace migrate --json');
            expect(agentsContent).not.toContain('npx --yes n8nac@next workspace status --json');
            expect(agentsContent).toContain('npx --yes @n8n-as-code/n8n-manager@next ...');
            expect(architectAgent).toContain('npx --yes @n8n-as-code/n8n-manager@next instance list');
            expect(architectSkill).toContain('npx --yes @n8n-as-code/n8n-manager@next instance list');
        });

        test('updates existing n8n block without duplication', async () => {
            const agentsPath = path.join(tempDir, 'AGENTS.md');

            await generator.generate(tempDir, '1.0.0');
            const run1 = fs.readFileSync(agentsPath, 'utf-8');
            expect(run1).toContain('1.0.0');

            await generator.generate(tempDir, '2.0.0');
            const run2 = fs.readFileSync(agentsPath, 'utf-8');

            expect(run2).toContain('2.0.0');
            expect(run2).not.toContain('1.0.0');
            expect(run2.match(/<!-- n8n-as-code-start -->/g)?.length).toBe(1);
        });

        test('does not duplicate effective config values into AGENTS.md', async () => {
            await generator.generate(tempDir, '1.0.0');

            const agentsContent = fs.readFileSync(path.join(tempDir, 'AGENTS.md'), 'utf-8');
            expect(agentsContent).not.toContain('Effective instance');
            expect(agentsContent).not.toContain('Active project');
            expect(agentsContent).not.toContain('Sync folder:');
            expect(agentsContent).not.toContain('Workspace-pinned instance');
        });

        test('allows overriding generated commands for local dev workspaces', async () => {
            const cliCmd = 'node /tmp/n8n-as-code/packages/cli/dist/index.js';
            const managerCmd = 'node /tmp/n8n-manager/packages/cli/dist/index.js';
            await generator.generate(tempDir, '1.0.0', undefined, {
                cliCommandOverride: cliCmd,
                managerCommandOverride: managerCmd,
            });

            const agentsContent = fs.readFileSync(path.join(tempDir, 'AGENTS.md'), 'utf-8');
            const architectAgent = fs.readFileSync(path.join(tempDir, '.github/agents/n8n-architect.agent.md'), 'utf-8');
            const architectSkill = fs.readFileSync(path.join(tempDir, '.agents/skills/n8n-architect/SKILL.md'), 'utf-8');

            expect(agentsContent).toContain(cliCmd);
            expect(agentsContent).toContain(managerCmd);
            expect(architectAgent).toContain(managerCmd);
            expect(architectSkill).toContain(cliCmd);
            expect(architectSkill).toContain(managerCmd);
            expect(architectSkill).toContain(`${cliCmd} skills`);
        });

        test('resolves generated CLI command from workspace dev config', async () => {
            const cliCmd = 'node /tmp/dev/n8n-as-code/packages/cli/dist/index.js';
            const previousEnvCommand = process.env.N8NAC_COMMAND;
            delete process.env.N8NAC_COMMAND;
            fs.writeFileSync(path.join(tempDir, '.n8nac-dev.json'), JSON.stringify({
                commands: { n8nac: cliCmd },
            }, null, 2));

            try {
                await generator.generate(tempDir, '1.0.0');

                const agentsContent = fs.readFileSync(path.join(tempDir, 'AGENTS.md'), 'utf-8');
                const architectSkill = fs.readFileSync(path.join(tempDir, '.agents/skills/n8n-architect/SKILL.md'), 'utf-8');

                expect(agentsContent).toContain(cliCmd);
                expect(architectSkill).toContain(cliCmd);
                expect(architectSkill).not.toContain('{{N8NAC_CMD}}');
            } finally {
                if (previousEnvCommand === undefined) {
                    delete process.env.N8NAC_COMMAND;
                } else {
                    process.env.N8NAC_COMMAND = previousEnvCommand;
                }
            }
        });

        test('prefers N8NAC_COMMAND over workspace dev config', async () => {
            const envCmd = 'node /tmp/env/n8n-as-code/packages/cli/dist/index.js';
            const workspaceCmd = 'node /tmp/dev/n8n-as-code/packages/cli/dist/index.js';
            const previousEnvCommand = process.env.N8NAC_COMMAND;
            process.env.N8NAC_COMMAND = envCmd;
            fs.writeFileSync(path.join(tempDir, '.n8nac-dev.json'), JSON.stringify({
                commands: { n8nac: workspaceCmd },
            }, null, 2));

            try {
                await generator.generate(tempDir, '1.0.0');

                const agentsContent = fs.readFileSync(path.join(tempDir, 'AGENTS.md'), 'utf-8');
                const architectSkill = fs.readFileSync(path.join(tempDir, '.agents/skills/n8n-architect/SKILL.md'), 'utf-8');

                expect(agentsContent).toContain(envCmd);
                expect(agentsContent).not.toContain(workspaceCmd);
                expect(architectSkill).toContain(envCmd);
                expect(architectSkill).not.toContain(workspaceCmd);
            } finally {
                if (previousEnvCommand === undefined) {
                    delete process.env.N8NAC_COMMAND;
                } else {
                    process.env.N8NAC_COMMAND = previousEnvCommand;
                }
            }
        });

        test('does not create legacy shim files', async () => {
            await generator.generate(tempDir, '1.0.0');

            expect(fs.existsSync(path.join(tempDir, 'n8nac-skills'))).toBe(false);
            expect(fs.existsSync(path.join(tempDir, 'n8nac-skills.cmd'))).toBe(false);
            expect(fs.existsSync(path.join(tempDir, 'n8nac'))).toBe(false);
            expect(fs.existsSync(path.join(tempDir, 'n8nac.cmd'))).toBe(false);
        });
    });

    describe('Canonical skill', () => {
        test('n8n-architect skill contains runtime/auth guardrails', () => {
            const content = generator.getAgentSkillContent('n8n-architect');

            expect(content).toContain('Managed Local Runtime');
            expect(content).toContain('--api-key-stdin');
            expect(content).toContain('Do not ask for host/API key when the user wants a managed local Docker instance.');
            expect(content).toContain('workflow present <workflowId> --json');
            expect(content).toContain('Do not call `npx --yes @n8n-as-code/n8n-manager presentWorkflowResult`');
            expect(content).not.toContain('{{N8N_MANAGER_CMD}}');
        });

        test('n8n-architect skill routes native MCP assist only for complementary live use cases', () => {
            const content = generator.getAgentSkillContent('n8n-architect');

            expect(content).toContain('The `n8n-as-code` MCP server is a client adapter for N8NAC tools.');
            expect(content).toContain('The native n8n MCP server is a separate live n8n instance endpoint.');
            expect(content).toContain('Default to local `npx --yes n8nac` for code-first workflow authoring, validation, pull, push');
            expect(content).toContain('Use `npx --yes n8nac skills` as the bundled offline knowledge default.');
            expect(content).toContain('Native MCP assist is configured per n8n-as-code environment. When creating or updating an environment, offer to configure it with `npx --yes n8nac native-mcp configure <environment> --token-stdin`; do not ask the user to manually configure a separate MCP server for Claude Code or the VS Code Workbench.');
            expect(content).toContain('Check native availability with `npx --yes n8nac native-mcp status --include-tools --json` before relying on native tools.');
            expect(content).toContain('For user requests about the current/live n8n instance, existing remote workflows, available nodes in this instance, credential metadata, projects, folders, executions, drift, or duplicate discovery, prefer native MCP read-only tools after the status check.');
            expect(content).toContain('Do not treat the presence of any MCP server as permission to call native n8n MCP tools.');
            expect(content).toContain('Native n8n MCP is used if and only if the generated execution or investigation strategy needs live n8n capabilities that local N8NAC cannot provide as well.');

            expect(content).toContain('Workflow authoring, editing, pull, push, sync, credentials, and durable workflow changes: use local');
            expect(content).toContain('Offline node knowledge, examples, documentation, and schema-first authoring: use local');
            expect(content).toContain('Live workflow discovery, drift investigation, projects, folders, credentials metadata, duplicate discovery, and execution inspection: prefer native MCP read-only tools when configured because the user is asking for current instance state.');
            expect(content).toContain('Connected-version node definitions or server-side validation: prefer native MCP read-only tools when the user asks what is available in this instance or needs validation against the connected n8n version.');
            expect(content).toContain('Runtime execution: prefer `npx --yes n8nac test` for real webhook, chat, or form trigger contracts; prefer native runtime execution only for explicit workflow-ID execution, non-webhook testing, native pin-data preparation, or direct execution diagnostics.');
            expect(content).toContain('Direct native workflow creation, update, publish, unpublish, archive, or destructive operations: do not use them as an automatic path; require an explicit direct-native request and sync-back plan.');

            expect(content).toContain('do not run it just because the tool exists');
            expect(content).toContain('Do not use native MCP create, update, publish, unpublish, archive, or destructive data-table tools');
            expect(content).toContain('N8NAC_NATIVE_MCP_ALLOW_REMOTE=1');
            expect(content).toContain('N8NAC_NATIVE_MCP_ALLOW_EXECUTION_DATA=1');
            expect(content).toContain('Never put native MCP tokens in project files, generated docs, command arguments, or responses.');
            expect(content).not.toContain('Default to native MCP');
        });

        test('n8n-architect skill contains workflow and schema-first guidance', () => {
            const content = generator.getAgentSkillContent('n8n-architect');

            expect(content).toContain('env status --json');
            expect(content).toContain('workflowsPath');
            expect(content).toContain('node-info <nodeName>');
            expect(content).toContain('ai_tool: [this.Tool.output]');
            expect(content).toContain('Reading Workflow Files Efficiently');
            expect(content).toContain('Common Mistakes To Avoid');
            expect(content).toContain('Credential Workflow');
            expect(content).toContain('Execution Debugging');
            expect(content).toContain('Operating Loop');
            expect(content).toContain('Workflow Presentation Contract');
            expect(content).toContain('Do not manually construct n8n workflow URLs');
            expect(content).toContain('workflow present <workflowId> --json');
            expect(content).not.toContain('{{N8NAC_CMD}}');
        });

        test('legacy OpenClaw-specific skill generator returns the canonical architect skill', () => {
            expect(generator.getOpenClawSkillContent()).toBe(generator.getSkillContent());
            expect(generator.getOpenClawSkillContent()).not.toContain('action: "skills"');
        });

        test('packaged plugin skills do not diverge from canonical generated skills', () => {
            const repoRoot = path.resolve(__dirname, '../../..');
            const pluginSkillRoots = [
                path.join(repoRoot, 'plugins/claude/n8n-as-code/skills'),
                path.join(repoRoot, 'plugins/openclaw/n8n-as-code/skills'),
                path.join(repoRoot, 'plugins/cursor/n8n-as-code/skills'),
            ];
            const distTag = resolveAdapterDistTag(repoRoot);

            for (const pluginRoot of pluginSkillRoots) {
                const expected = {
                    'n8n-architect': generator.getAgentSkillContent('n8n-architect', distTag),
                };
                for (const skillName of Object.keys(expected) as Array<keyof typeof expected>) {
                    const skillPath = path.join(pluginRoot, skillName, 'SKILL.md');
                    expect(fs.existsSync(skillPath)).toBe(true);
                    expect(fs.readFileSync(skillPath, 'utf8')).toBe(expected[skillName]);
                }
            }
        });
    });
});

function resolveAdapterDistTag(repoRoot: string): string | undefined {
    const explicit = process.env.N8NAC_SKILL_ADAPTER_DIST_TAG?.trim();
    if (explicit) {
        return ['stable', 'latest', 'none'].includes(explicit) ? undefined : explicit;
    }

    if (process.env.GITHUB_BASE_REF === 'main') {
        return undefined;
    }

    const versions = [
        path.join(repoRoot, 'packages/cli/package.json'),
        path.join(repoRoot, 'packages/skills/package.json'),
    ].map((packagePath) => JSON.parse(fs.readFileSync(packagePath, 'utf8')).version as string);

    if (versions.some((version) => version.includes('-next'))) {
        return 'next';
    }

    const branch = process.env.GITHUB_REF_NAME || process.env.BRANCH_NAME || readGitBranch(repoRoot);
    return branch === 'next' ? 'next' : undefined;
}

function readGitBranch(repoRoot: string): string | undefined {
    try {
        return execFileSync('git', ['branch', '--show-current'], {
            cwd: repoRoot,
            encoding: 'utf8',
            stdio: ['ignore', 'pipe', 'ignore'],
        }).trim();
    } catch {
        return undefined;
    }
}
